name: Node.js CI

on:
    push:
        branches:
            - next
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Restore Yarn cache
              uses: actions/cache@v3
              with:
                  path: .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Yarn
              run: corepack enable

            - name: Install Yarn Dependencies
              run: yarn install --immutable

            - name: Compile
              run: yarn build

    lint:
        name: Run Linter
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Restore Yarn cache
              uses: actions/cache@v3
              with:
                  path: .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Yarn
              run: corepack enable

            - name: Install Yarn Dependencies
              run: yarn install --immutable

            - name: Run ESLint
              run: yarn eslint --ext .js,.jsx,.ts,.tsx
